---
# changes of prefs.js will otherwise have no effect if Firefox is still running
- name: fail if firefox is running
  shell: "! pgrep -U {{ ansible_user_id }} ^firefox$"

- name: set distro-specific variables
  include_vars: "{{ lookup('ansible.builtin.first_found', params) }}"
  vars:
    params:
      files:
        - '{{ ansible_distribution|lower }}.yml'
        - default.yml
      paths:
        - '{{ role_path }}/vars'

- name: find all firefox profiles
  find:
    paths:
      - "{{ firefox_config_dir }}"
      - "{{ firefox_profiles_dir }}"
    file_type: any
    patterns: '*.default*,profile-*'
  register: firefox_profile_dirs

- name: create the user configuration if it doesn't exist
  file:
    state: touch
    path: '{{ item.path }}/prefs.js'
  with_items: "{{ firefox_profile_dirs.files }}"

- name: copy the user configuration
  copy:
    src: "user.js"
    dest: "{{ item.path }}/user.js"
  loop: "{{ firefox_profile_dirs.files }}"

- name: prepare a virtual environment
  pip:
    virtualenv: "{{ role_path }}/.venv"
    virtualenv_python: python3.8
    name: "patzm-scripts @ git+https://github.com/patzm/scripts@v0.0.4"

- name: attempt to synchronize user dictionaries
  ignore_errors: yes
  script:
    chdir: "{{ role_path }}/.venv/bin"
    cmd: "'{{ item.path }}/persdict.dat'"
    executable: "{{ role_path }}/.venv/bin/firefox-sync"
  with_items: "{{ firefox_profile_dirs.files }}"
