---
# changes of prefs.js will otherwise have no effect if Firefox is still running
- name: fail if firefox is running
  shell: "! pgrep -U {{ ansible_user_id }} ^firefox$"

- name: set distro-specific variables
  include_vars: "{{ lookup('ansible.builtin.first_found', params) }}"
  vars:
    params:
      files:
        - '{{ ansible_distribution|lower }}.yml'
        - default.yml
      paths:
        - '{{ role_path }}/vars'

- name: find all firefox profiles
  find:
    paths: "{{ firefox_config_dir }}"
    file_type: any
    patterns: '*.default*'
  register: firefox_profile_dirs

- name: create the user configuration if it doesn't exist
  file:
    state: touch
    path: '{{ item.path }}/prefs.js'
  with_items: "{{ firefox_profile_dirs.files }}"

- name: edit the user configuration
  script: "set-pref '{{ item[0].path }}/prefs.js' {{ item[1].key }} {{ item[1].value }}"
  with_nested:
    - "{{ firefox_profile_dirs.files }}"
    - [
        {key: "browser.fullscreen.exit_on_escape", value: "false"},
        {key: "browser.tabs.closeWindowWithLastTab", value: "false"},
        {key: "privacy.webrtc.legacyGlobalIndicator", value: "false"},
        {key: "privacy.webrtc.hideGlobalIndicator", value: "true"},
        {key: "mousewheel.with_control.action", value: 1},
        {key: "places.frecency.bookmarkVisitBonus", value: 1000},
        {key: "places.frecency.unvisitedBookmarkBonus", value: 1000},
      ]
