[font]
size = 12

[font.normal]
family = "MesloLGS NF"

[[keyboard.bindings]]
chars = "\u001BF"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BB"
key = "Left"
mods = "Alt"

[[hints.enabled]]
regex = "(mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
command = "<open-command>"
post_processing = true

[hints.enabled.mouse]
enabled = true
mods = "Control"

[window]
dynamic_padding = true
opacity = 0.8

[window.dimensions]
columns = 133
lines = 40

[window.padding]
x = 10
y = 10
