#!/usr/bin/env bash

# Install the XCode developer tools
xcode-select --install

# Install brew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

/opt/homebrew/bin/brew update

# Install ansible
/opt/homebrew/bin/brew install ansible
