#!/usr/bin/env bash

# Install the XCode developer tools
xcode-select --install

# Install brew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

if [[ $(uname -m) == 'arm64' ]]; then
	brew_bin=/opt/homebrew/bin/brew
else
	brew_bin=/usr/local/bin/brew
fi

${brew_bin} update

# Install ansible
${brew_bin} install ansible
