---
- name: run setup
  hosts: "{{ custom_hosts|default('localhost') }}"
  gather_facts: yes

  vars_files:
    - 'vars/common.yml'
    - ['vars/{{ ansible_distribution|lower }}-{{ ansible_distribution_major_version }}.yml',
       'vars/{{ ansible_distribution|lower }}.yml',
       'vars/unix.yml']

  roles:
    - role: scripts
      tags: dotfiles
    - role: packages
      tags: [packages, i3]
    - role: terminals
    - role: firefox
      tags: dotfiles
    - role: git
      tags: dotfiles
    - role: ZSH
    - role: vim
      tags: dotfiles
    - role: tmux
      tags: dotfiles
    - role: htop
      tags: dotfiles
    - role: ranger
      tags: dotfiles
    - role: sublime
      tags: dotfiles
    - role: python
    - role: i3-gaps
      tags: i3
