---
- name: run setup
  hosts: "{{ custom_hosts|default('localhost') }}"
  gather_facts: yes

  vars_files:
    - 'vars/common.yml'
    - [
        'vars/{{ ansible_distribution|lower }}-{{ ansible_architecture }}.yml',
        'vars/{{ ansible_distribution|lower }}.yml',
        'vars/unix.yml'
      ]

  pre_tasks:
    - name: Find the most preferred editor executable
      tags: always
      block:
        - name: Check for available editors using a loop
          shell: "command -v {{ item }}"
          loop: "{{ vim_distros }}"
          register: editor_check
          ignore_errors: true

        - name: Set editor variable with the first successful command
          set_fact:
            editor: "{{ editor_check.results|
                        selectattr('rc', 'equalto', 0)|
                        map(attribute='stdout')|
                        first }}"

  roles:
    - role: packages
      tags: [packages, i3, sway]
    - role: fonts
      tags: dotfiles
    - role: git
      tags: dotfiles
    - role: i3-gaps
      tags: i3
    - role: htop
      tags: dotfiles
    - role: os-settings
      tags: dotfiles
    - role: python
      tags: dotfiles
    - role: ranger
      tags: dotfiles
    - role: scripts
      tags: ui
    - role: sublime
      tags: dotfiles
    - role: sway
    - role: yabai
      tags: dotfiles
    - role: terminals
    - role: tmux
      tags: dotfiles
    - role: vim
      tags: dotfiles
    - role: ZSH
      tags: dotfiles
    - role: firefox
      tags: browser
