---
- name: run setup
  hosts: "{{ custom_hosts|default('localhost') }}"
  gather_facts: yes

  vars_files:
    - 'vars/common.yml'
    - [
        'vars/{{ ansible_distribution|lower }}-{{ ansible_architecture }}.yml',
        'vars/{{ ansible_distribution|lower }}.yml',
        'vars/unix.yml'
      ]

  roles:
    - role: packages
      tags: [packages, i3, sway]
    - role: firefox
      tags: dotfiles
    - role: git
      tags: dotfiles
    - role: i3-gaps
      tags: i3
    - role: htop
      tags: dotfiles
    - role: os-settings
      tags: dotfiles
    - role: python
      tags: dotfiles
    - role: ranger
      tags: dotfiles
    - role: scripts
      tags: ui
    - role: sublime
      tags: dotfiles
    - role: sway
    - role: terminals
    - role: tmux
      tags: dotfiles
    - role: vim
      tags: dotfiles
    - role: ZSH
