---
- name: "run the platform dependent tasks in {{ ansible_distribution }}"
  include_tasks: 'execute_task.yml'
  vars:
    task_prefix: "{{ ansible_distribution|lower }}"
  loop_control:
    loop_var: task
  with_items:
    - 'main'
    - '{{ ansible_distribution_major_version|lower }}' 
  tags: always
