---
- name: "run the platform dependent tasks in {{ ansible_distribution }}"
  include_tasks: 'execute_task.yml'
  vars:
    task_prefix: "{{ ansible_distribution|lower }}"
  loop_control:
    loop_var: task
  with_items:
    - 'main'
    - '{{ ansible_distribution_major_version|lower }}' 

- name: Find the location of the zsh executable
  shell: which zsh
  register: zsh_bin

- name: Make ZSH default shell
  become: yes
  user:
    name: "{{ ansible_env.USER }}"
    shell: "{{ zsh_bin.stdout }}"
