---
- name: Create the config directories
  file:
    path: '{{ user_config_dir }}/{{ item }}'
    state: directory
  loop:
    - yabai
    - skhd

- name: Copy the yabai configuration
  copy:
    src: 'yabairc.sh'
    dest: '{{ user_config_dir }}/yabai/yabairc'

- name: Copy the skhd configuration
  copy:
    src: 'skhdrc.sh'
    dest: '{{ user_config_dir }}/skhd/skhdrc'
