---
- name: installing core packages
  become: yes
  package: name={{ item }} state=latest
  with_items:
    - alacritty
    - blueman
    - bmon
    - curl
    - deepin-calculator
    - exiv2
    - feh
    - git
    - gnome-keyring
    - hsetroot
    - htop
    - imagemagick
    - libsecret
    - libva-intel-driver
    - neofetch
    - neovim
    - network-manager-applet
    - networkmanager
    - python-pip  # Python 3
    - python-virtualenv
    - python-virtualenvwrapper
    - ranger
    - rxvt-unicode
    - tmux
    - tree
    - ttf-cascadia-code
    - unrar
    - urxvt-perls
    - vim
    - wget
    - wmctrl
    - xclip
    - zsh

- name: create the yay config folder
  file:
    path: '{{ yay_config_dir }}'
    state: directory


- name: copy yay config files
  copy:
    src: '{{ role_path }}/files/archlinux/yay/config.json'
    dest: '{{ yay_config_file }}'
    owner: "{{ ansible_env.USER }}"
    group: "{{ user_group }}"
    force: yes

- name: install powerline fonts
  command: yay --answerdiff=None --noconfirm --needed -S powerline-fonts-git

- name: install emoji fonts
  command: yay --answerdiff=None --noconfirm --needed -S ttf-joypixels

- name: install Python3.7
  command: yay --answerdiff=None --noconfirm --needed -S python37
