---
- name: installing core packages
  become: yes
  apt:
    update_cache: yes
    pkg:
      - git
      - hsetroot
      - htop
      - iotop
      - make
      - neofetch
      - neovim
      - network-manager
      - python3-pip
      - rename
      - rxvt-unicode
      - sshfs
      - tmux
      - tree
      - wget
      - zsh

- name: check if pyenv is already installed
  stat:
    path: "{{ user_home_dir }}/.pyenv/bin/pyenv"
  register: pyenv_exists

- name: install pyenv dependencies
  become: yes
  apt:
    update_cache: yes
    pkg:
      - build-essential
      - curl
      - libbz2-dev
      - libffi-dev
      - liblzma-dev
      - libncurses5-dev
      - libncursesw5-dev
      - libreadline-dev
      - libsqlite3-dev
      - libssl-dev
      - llvm
      - tk-dev
      - wget
      - xz-utils
      - zlib1g-dev

- name: install pyenv
  shell: "curl https://pyenv.run | bash"
  when: not pyenv_exists.stat.exists

- name: install pyenv-virtualenv
  git:
    repo: https://github.com/pyenv/pyenv-virtualenv.git
    dest: "{{ user_home_dir }}/.pyenv/plugins/pyenv-virtualenv"
    version: master

- name: install pyenv-virtualenvwrapper
  git:
    repo: https://github.com/pyenv/pyenv-virtualenvwrapper.git
    dest: "{{ user_home_dir }}/.pyenv/plugins/pyenv-virtualenvwrapper"
    version: master
