#!/usr/bin/env bash

NOTE_DIR="${HOME}/Documents/notes/$(date +"%Y-%m-%d")"

if [ ! -d "${NOTE_DIR}" ]; then
	mkdir -p ${NOTE_DIR}
fi

nvim "${NOTE_DIR}/$(date +"%H-%M-%S").md"

# vim: set filetype=sh : 
