---
- name: installing core packages
  become: yes
  package: name={{ item }} state=latest
  with_items:
    - bmon
    - curl
    - exiv2
    - git
    - htop
    - imagemagick
    - ncurses
    - neovim
    - py3-pip
    - py3-virtualenv
    - python3-dev
    - ranger
    - tmux
    - tree
    - unrar
    - util-linux
    - vim
    - wget
    - xclip
    - zsh
    - zsh-vcs

- name: python virtualenvwrapper
  become: yes
  pip:
    name: virtualenvwrapper
    executable: pip3
