---
- name: create directory for virtual environments
  file:
    path: '{{ user_home_dir }}/.venvs'
    state: directory

- name: "install python {{ default_python_version }}"
  command: 'pyenv install -s {{ default_python_version }}'

- name: "set {{ default_python_version }} as the global pyenv version"
  command: 'pyenv global {{ default_python_version }}'

- name: "install virtualenv and virtualenvwrapper"
  command: 'pyenv exec pip install virtualenv virtualenvwrapper'

- name: create the bpython config folder
  file:
    path: '{{ bpython_config_dir }}'
    state: directory

- name: copy the bpython config file
  copy:
    src: '{{ role_path }}/files/bpython/config'
    dest: '{{ bpython_config_dir }}/config'
    force: yes


- name: create the virtualenvwrapper config directory
  file:
    path: "{{ virtualenvwrapper_config_dir }}"
    state: directory

- name: copy the virtualenvwrapper configurations
  copy:
    src: "{{ item }}"
    dest: "{{ virtualenvwrapper_config_dir }}"
  with_fileglob: "virtualenvwrapper/*"
