#!/bin/sh

lock() {
    i3lock
}

case "$1" in
    lock)
        lock
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        lock && pm-suspend
        ;;
    hibernate)
        lock && pm-hibernate
        ;;
    reboot)
       shutdown -r now 
        ;;
    shutdown)
       shutdown -P now 
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0

