---
- name: Create the ZSH config dir
  file:
    path: '{{ zsh_config_dir }}'
    state: directory

- name: Copy default ZSH instance if it doesn't exist
  copy:
    src: 'instance.zsh'
    dest: '{{ zsh_config_dir }}/zshinstance'
    force: no

- name: Copy the ZSH config files
  copy:
    src: '{{ item }}'
    dest: '{{ zsh_config_dir }}/{{ item }}'
  loop:
    - .zshrc
    - .p10k.zsh

- name: Copy the OS dependent configuration
  copy:
    src: 'os_{{ ansible_os_family|lower }}.zsh'
    dest: '{{ zsh_config_dir }}/zshosdep'
    owner: "{{ ansible_env.USER }}"

- name: Copy the environment variable file
  copy:
    src: 'env.zsh'
    dest: '{{ user_home_dir }}/.zshenv'

- name: Copy the aliases
  copy:
    src: 'bash_aliases.sh'
    dest: '{{ user_home_dir }}/.bash_aliases'

- name: check if Oh My Zsh is already installed
  stat:
    path: "{{ omz_installation_dir }}"
  register: omz_dir

- name: create the Oh My Zsh install script file
  tempfile:
    state:  file
    prefix: ansible.omz_install_
    suffix: .sh
  register: omz_install_script
  when: not omz_dir.stat.exists

- name: download the Oh My Zsh install script
  get_url:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: '{{ omz_install_script.path }}'
    validate_certs: no
  when: not omz_dir.stat.exists

- name: install Oh My Zsh
  shell: "sh {{ omz_install_script.path }} --unattended --keep-zshrc"
  when: not omz_dir.stat.exists

- name: copy the Oh My Zsh plugin & theme downloader
  copy:
    src: 'omz_setup.zsh'
    dest: '{{ omz_installation_dir }}/omz-setup'
    mode: preserve
