---
- name: Find the location of the zsh executable
  shell: which zsh
  register: zsh_bin
  tags: packages

- name: Make ZSH default shell
  become: yes
  user:
    name: "{{ ansible_env.USER }}"
    shell: "{{ zsh_bin.stdout }}"
  tags: packages

- name: Copy default ZSH instance if it doesn't exist
  copy:
    src: '{{ role_path }}/files/.zshinstance'
    dest: '{{ user_home_dir }}/.zshinstance'
    owner: "{{ ansible_env.USER }}"
    mode: 0700
    force: no
  tags: dotfiles

- name: Copy default ZSH config
  copy:
    src: '{{ role_path }}/files/.zshrc'
    dest: '{{ user_home_dir }}/.zshrc'
    owner: "{{ ansible_env.USER }}"
    mode: 0700
    force: yes
  tags: dotfiles

- name: Copy the OS dependent configuration
  copy:
    src: '{{ role_path }}/files/.zsh_{{ ansible_os_family|lower }}'
    dest: '{{ user_home_dir }}/.zshosdep'
    owner: "{{ ansible_env.USER }}"
    mode: 0700
    force: yes
  tags: dotfiles

- name: Copy the aliases
  copy:
    src: '{{ role_path }}/files/.bash_aliases'
    dest: '{{ user_home_dir }}/.bash_aliases'
    owner: "{{ ansible_env.USER }}"
    mode: 0700
    force: yes
  tags: dotfiles
