---
- name: Create the ZSH config dir
  file:
    path: '{{ zsh_config_dir }}'
    state: directory

- name: Copy default ZSH instance if it doesn't exist
  copy:
    src: 'instance.zsh'
    dest: '{{ zsh_config_dir }}/zshinstance'
    force: no

- name: Copy the ZSH config files
  copy:
    src: '{{ item }}'
    dest: '{{ zsh_config_dir }}/{{ item }}'
  loop:
    - .zshrc
    - .p10k.zsh

- name: Copy the OS dependent configuration
  copy:
    src: 'os_{{ ansible_os_family|lower }}.zsh'
    dest: '{{ zsh_config_dir }}/zshosdep'
    owner: "{{ ansible_env.USER }}"

- name: Copy the environment variable file
  copy:
    src: 'env.zsh'
    dest: '{{ user_home_dir }}/.zshenv'

- name: Copy the aliases
  copy:
    src: 'bash_aliases.sh'
    dest: '{{ user_home_dir }}/.bash_aliases'

