---
- name: enable long-press character accent menu
  command: "defaults write {{ item }}"
  loop:
    - "-g ApplePressAndHoldEnabled -bool true"
    - "com.jetbrains.intellij ApplePressAndHoldEnabled -bool false"
    - "com.jetbrains.intellij.ce ApplePressAndHoldEnabled -bool false"
    - "com.jetbrains.pycharm ApplePressAndHoldEnabled -bool false"
    - "com.jetbrains.pycharm.ce ApplePressAndHoldEnabled -bool false"

- name: enable Window movement with hotkey Ctrl+CMD and drag
  command: "defaults write -g NSWindowShouldDragOnGesture -bool true"

- name: copy the automatic ssh-add invocation
  copy:
    src: "macosx/ssh-add.plist"
    dest: "{{ user_home_dir }}/Library/LaunchAgents/ssh-add.plist"
