---
- name: "include the task list for {{ ansible_distribution|lower }}"
  include_tasks: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution|lower }}.yml"
      skip: true
