---
- name: install polybar dependencies
  become: yes
  package: name={{ item }} state=latest
  with_items:
    - gcc
    - cmake
    - cmake-data
    - pkg-config
    - libcairo2-dev
    - libxcb1-dev
    - libxcb-util0-dev
    - libxcb-randr0-dev
    - python-xcbgen
    - xcb-proto
    - libxcb-image0-dev
    - libxcb-ewmh-dev
    - libxcb-icccm4-dev
    - libxcb-xkb-dev
    - libxcb-xrm-dev
    - libxcb-cursor-dev
    - libasound2-dev
    - libpulse-dev
    - libjsoncpp-dev
    - libmpdclient-dev
    - libcurl4-openssl-dev
    - libiw-dev
    - libnl-3-dev
  tags: i3

- name: create temporary checkout directory
  tempfile: state=directory suffix=.polybar
  register: polybar_repo_dir
  tags: i3

- name: clone the git repository
  git:
    repo: https://github.com/jaagr/polybar.git
    dest: '{{ polybar_repo_dir.path }}'
    version: 3.2.1
  tags: i3

- name: create temporary build directory
  file:
    path: '{{ polybar_repo_dir.path }}/build'
    state: directory
  tags: i3

- name: configure with cmake
  shell: 'cmake {{ polybar_repo_dir.path }}'
  args:
    chdir: '{{ polybar_repo_dir.path }}/build'
  tags: i3

- name: make and install
  become: yes
  make:
    chdir: '{{ polybar_repo_dir.path }}/build'
    target: install
    params:
      NUM_THREADS: "{{ ansible_processor_vcpus }}"
  tags: i3
