""""""""""""""""""""""""""""""
" Plugin management
call plug#begin()

" Let plug manage itself:
Plug 'gmarik/plug'

Plug 'hzchirs/vim-material'
Plug 'godlygeek/tabular'

" Markdown support
Plug 'plasticboy/vim-markdown'
Plug 'JamshedVesuna/vim-markdown-preview'

" Python
Plug 'vim-scripts/indentpython.vim'
Plug 'vim-syntastic/syntastic'
Plug 'nvie/vim-flake8'
Plug 'plytophogy/vim-virtualenv'

" Just a shitload of color schemes.
" https://github.com/flazz/vim-colorschemes#current-colorschemes
Plug 'flazz/vim-colorschemes'

" Fuzzy finder -- absolutely must have.
Plug 'kien/ctrlp.vim'

" Support for easily toggling comments.
Plug 'tpope/vim-commentary'

" Proper JSON filetype detection, and support.
Plug 'leshill/vim-json'

" Ansible yaml
Plug 'chase/vim-ansible-yaml'

" git wrapper
Plug 'tpope/vim-fugitive'

" directory tree with git support
Plug 'scrooloose/nerdtree'
Plug 'Xuyuanp/nerdtree-git-plugin'

" airline statusline
Plug 'bling/vim-airline'

" vim surround
Plug 'tpope/vim-surround'

" Auto-complete
Plug 'autozimu/LanguageClient-neovim', {
    \ 'branch': 'next',
    \ 'do': 'bash install.sh',
    \ }
Plug 'junegunn/fzf'

call plug#end()
filetype plugin indent on

" Load the base vim configuration
source ~/.vim/vimrcbase

set nocompatible " Fuck VI... That's for grandpas.
filetype off

" Syntax highlighting
syntax on
let g:python_highlight_all=1

" Use sane regex's when searching
nnoremap / /\v
vnoremap / /\v

" Prefer tabs instead of buffers
set switchbuf=usetab,newtab

" We have VCS -- we don't need this stuff.
set nobackup " We have vcs, we don't need backups.
set nowritebackup " We have vcs, we don't need backups.
set noswapfile " They're just annoying. Who likes them?

" Set the copy buffer to be CLIPBOARD
set clipboard=unnamedplus

" Enable folding with za
set foldmethod=indent
set foldlevel=99

" Generic
set nu
set fileformat=unix

" Python settings
au BufNewFile,BufRead *.py
    \ set tabstop=4 |
    \ set softtabstop=4 |
    \ set shiftwidth=4 |
    \ set expandtab |
    \ set autoindent
highlight BadWhitespace ctermbg=red guibg=darkred
au BufNewFile,BufRead *.py,*.pyw,*.c,*.h match BadWhitespace /\s\+$/
set encoding=utf-8

" Jenkinsfile
au BufNewFile,BufRead Jenkinsfile setf groovy

" Yaml files
au BufNewFile,BufRead *.yml,*.yaml
	\ set tabstop=2 |
    \ set softtabstop=2 |
    \ set shiftwidth=2 |
	\ set expandtab |
	\ set autoindent

""""""""""""""""""""""""""""""
" Plugin settings            "
""""""""""""""""""""""""""""""

" Configure NERDTree
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 1 && isdirectory(argv()[0]) && !exists("s:std_in") | exe 'NERDTree' argv()[0] | wincmd p | ene | endif
nnoremap <C-n> :NERDTreeToggle<CR>
let NERDTreeMinimalUI = 1
let NERDTreeShowHidden = 1
let NERDTreeIgnore=['\.pyc$', '\~$']

" Set the maximum number of CtrlP results
let g:ctrlp_max_height = 15
nnoremap <A-p> :<C-U>CtrlPBuffer<CR>
set wildignore+=*.pyc

" Finally the color scheme. Choose whichever you want from the list in the
" link above (back up where we included the bundle of a ton of themes.)
if isdirectory("~/.vim/bundle/vim-material")
    colorscheme vim-material
endif

