---
- name: copy the tmux configuration
  copy:
    src: '{{ role_path }}/files/tmux.conf'
    dest: '{{ user_home_dir }}/.tmux.conf'
    force: yes

- name: create the tmux plugin directory
  file:
    path: '{{ tpm_dir }}'
    state: directory
    mode: 0700

- name: clone tpm (tmux plugin manager)
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: '{{ tpm_dir }}'
    force: yes

- name: install and update all plugins
  shell: |
    tmux new-session -d -s plugin
    '{{ tpm_dir }}/scripts/install_plugins.sh'
    '{{ tpm_dir }}/scripts/update_plugin.sh all'
    tmux kill-session -t plugin
  environment: "{{ env }}"
