---
- name: create the Sublime-Text config folder
  file:
    path: '{{ st_config_dir }}'
    state: directory

- name: copy the configuration files
  copy:
    src: '{{ item }}'
    dest: '{{ st_config_dir }}'
  with_fileglob:
    - '*.sublime-settings'
