---
- name: install the required packages
  package:
    name: '{{ item }}'
    state: latest
  loop:
    - gdm
    - gnome-keyring
    - gnome-session
    - kanshi
    - light-locker
  tags: sway

- name: copy the sway config files / directories
  copy:
    src: '{{ item }}'
    dest: '{{ sway_config_dir }}/{{ item }}'
  loop:
    - 'config'
    - '{{ sway_rel_config_include_dir }}/'
    - '{{ sway_rel_definition_include_dir }}/'
    - '{{ sway_rel_modes_include_dir }}/'
  tags: sway,dotfiles-sway

- name: create the environment variables folder
  file:
    path: '{{ environment_config_dir }}'
    state: directory
  tags: sway,dotfiles-sway

- name: copy environment config files
  copy:
    src: dotfiles.conf
    dest: '{{ environment_config_dir }}/dotfiles.conf'
  tags: sway,dotfiles-sway

- name: copy the .bash_profile file
  copy:
    src: .bash_profile
    dest: '{{ user_home_dir }}/.bash_profile'
  tags: sway,dotfiles-sway

- name: install scripts
  import_role:
    name: scripts
  tags: sway,dotfiles-sway
