---
- name: install the required packages
  package:
    name: '{{ item }}'
    state: latest
  loop:
    - accountsservice  # required for LightDM
    - gnome-keyring
    - kanshi
    - lightdm
    - lightdm-gtk-greeter
    - light-locker
    - xorg-server  # required for LightDM
  tags: sway

- name: copy the sway config files / directories
  copy:
    src: '{{ item }}'
    dest: '{{ sway_config_dir }}/{{ item }}'
  loop:
    - 'config'
    - '{{ sway_rel_config_include_dir }}/'
    - '{{ sway_rel_definition_include_dir }}/'
  tags: sway,dotfiles-sway

- name: create the environment variables folder
  file:
    path: '{{ environment_config_dir }}'
    state: directory
  tags: sway,dotfiles-sway

- name: copy environment config files
  copy:
    src: dotfiles.conf
    dest: '{{ environment_config_dir }}/dotfiles.conf'
  tags: sway,dotfiles-sway

- name: copy the .xprofile file
  copy:
    src: .xprofile
    dest: '{{ user_home_dir }}/.xprofile'
  tags: sway,dotfiles-sway

- name: install scripts
  import_role:
    name: scripts
  tags: sway,dotfiles-sway
