---
- name: make sure the htop config folder exists
  file:
    path: '{{ htop_config_dir }}'
    state: directory
    mode: 0700

- name: copy the htop config file
  copy:
    src: '{{ role_path }}/files/htoprc'
    dest: '{{ htop_config_dir }}/htoprc'
    force: yes
