---
- name: installing core packages
  become: yes
  package: name={{ item }} state=latest
  with_items:
    - blueman
    - bmon
    - checkinstall
    - curl
    - exiv2
    - feh
    - gconf-service
    - gconf2
    - git
    - hsetroot
    - htop
    - imagemagick
    - libimage-exiftool-perl
    - libssl-dev
    - lm-sensors
    - ntfs-3g
    - python3-pip
    - python3-virtualenv
    - ranger
    - rename
    - rxvt-unicode
    - sshfs
    - tree
    - unrar
    - wget
    - wmctrl
    - xclip
    - zsh
