---
- name: installing core packages
  become: yes
  apt:
    update_cache: yes
    pkg:
      - blueman
      - bmon
      - build-essential
      - checkinstall
      - cmake
      - curl
      - exiv2
      - feh
      - gconf-service
      - gconf2
      - git
      - hsetroot
      - htop
      - imagemagick
      - libbz2-dev
      - libffi-dev
      - libimage-exiftool-perl
      - liblzma-dev
      - libncursesw5-dev
      - libreadline-dev
      - libsqlite3-dev
      - libssl-dev
      - libxml2-dev
      - libxmlsec1-dev
      - llvm
      - lm-sensors
      - make
      - neofetch
      - neovim
      - network-manager
      - ntfs-3g
      - python3-pip
      - ranger
      - rename
      - rxvt-unicode
      - sshfs
      - tk-dev
      - tmux
      - tree
      - unrar
      - wget
      - wmctrl
      - xclip
      - xz-utils
      - zlib1g-dev
      - zsh

- name: check if pyenv is already installed
  stat:
    path: "{{ user_home_dir }}/.pyenv/bin/pyenv"
  register: pyenv_exists


- name: install pyenv
  shell: "curl https://pyenv.run | bash"
  when: not pyenv_exists.stat.exists

- name: install pyenv-virtualenv
  git:
    repo: https://github.com/pyenv/pyenv-virtualenv.git
    dest: "{{ user_home_dir }}/.pyenv/plugins/pyenv-virtualenv"
    version: master

- name: install pyenv-virtualenvwrapper
  git:
    repo: https://github.com/pyenv/pyenv-virtualenvwrapper.git
    dest: "{{ user_home_dir }}/.pyenv/plugins/pyenv-virtualenvwrapper"
    version: master
