"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

format = """$time$all"""

[time]
disabled = false
format = '[\[🕙 $time \]]($style) '
time_format = '%v %T'
utc_time_offset = 'local'

