---
- name: install the MesloLGS NF (nerd-font)
  copy:
    src: '{{ item }}'
    dest: '{{ user_local_dir }}/share/fonts'
  with_fileglob: 'meslo-nerd-font/*.ttf'

- name: update font-cache
  command: fc-cache -fv
